{
 "title": "RebrainMe Global Corporation",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "grafana_node_job",
    "label": "Grafana_Node_Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "grafana_instance", "label": "Grafana_Instance", "query": { "query": "grafana_build_info" } },
   {
    "name": "postgres_instance",
    "query": {
     "query": "label_values(up{job=~\"postgres_ex\"},instance)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{instance=\"$postgres_instance\",datname!~\"template.*|postgres\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TSDB series ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "QPS Prometheus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "CPU Prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait "
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs "
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other "
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"prom_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle "
    }
   ]
  },
  {
   "title": "Memory Prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prom_node_ex\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prom_node_ex\"} - node_memory_MemFree_bytes{job=\"prom_node_ex\"} - (node_memory_Cached_bytes{job=\"prom_node_ex\"} + node_memory_Buffers_bytes{job=\"prom_node_ex\"} + node_memory_SReclaimable_bytes{job=\"prom_node_ex\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"prom_node_ex\"} + node_memory_Buffers_bytes{job=\"prom_node_ex\"} + node_memory_SReclaimable_bytes{job=\"prom_node_ex\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"prom_node_ex\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"prom_node_ex\"} - node_memory_SwapFree_bytes{job=\"prom_node_ex\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Prometheus",
   "type": "graph",
   "description": "Network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"prom_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"prom_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"prom_node_ex\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"prom_node_ex\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "PostgresSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{job=\"postgres_ex\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"postgres\",job=\"postgres_ex\",state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "QPS Postgres",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=~\"$db\",instance=\"$postgres_instance\"}[1m])) + sum(rate(pg_stat_database_xact_rollback{datname=~\"$db\",instance=\"$postgres_instance\"}[1m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait "
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs "
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other "
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"postgres_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle "
    }
   ]
  },
  {
   "title": "Memory Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"postgres_node_ex\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"postgres_node_ex\"} - node_memory_MemFree_bytes{job=\"postgres_node_ex\"} - (node_memory_Cached_bytes{job=\"postgres_node_ex\"} + node_memory_Buffers_bytes{job=\"postgres_node_ex\"} + node_memory_SReclaimable_bytes{job=\"postgres_node_ex\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"postgres_node_ex\"} + node_memory_Buffers_bytes{job=\"postgres_node_ex\"} + node_memory_SReclaimable_bytes{job=\"postgres_node_ex\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"postgres_node_ex\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"postgres_node_ex\"} - node_memory_SwapFree_bytes{job=\"postgres_node_ex\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Postgres",
   "type": "graph",
   "description": "Network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"postgres_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"postgres_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Postgres",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"postgres_node_ex\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"postgres_node_ex\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Grafana users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=~\"$grafana_instance\"}"
    }
   ]
  },
  {
   "title": "Grafana Organisations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=~\"$grafana_instance\"}"
    }
   ]
  },
  {
   "title": "Grafana Dashboards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=~\"$grafana_instance\"} "
    }
   ]
  },
  {
   "title": "Grafana Page Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "grafana_page_response_status_total{instance=~\"$grafana_instance\"}",
     "legendFormat": "{{job}} code = {{code}}"
    }
   ]
  },
  {
   "title": "Grafana Api Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "grafana_api_response_status_total{instance=~\"$grafana_instance\"}",
     "legendFormat": "{{job}} code = {{code}}"
    }
   ]
  },
  {
   "title": "CPU Grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait "
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs "
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other "
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"$grafana_node_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle "
    }
   ]
  },
  {
   "title": "Memory Grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$grafana_node_job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$grafana_node_job\"} - node_memory_MemFree_bytes{job=\"$grafana_node_job\"} - (node_memory_Cached_bytes{job=\"$grafana_node_job\"} + node_memory_Buffers_bytes{job=\"$grafana_node_job\"} + node_memory_SReclaimable_bytes{job=\"$grafana_node_job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$grafana_node_job\"} + node_memory_Buffers_bytes{job=\"$grafana_node_job\"} + node_memory_SReclaimable_bytes{job=\"$grafana_node_job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$grafana_node_job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"$grafana_node_job\"} - node_memory_SwapFree_bytes{job=\"$grafana_node_job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Grafana",
   "type": "graph",
   "description": "Network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$grafana_node_job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"$grafana_node_job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Grafana",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$grafana_node_job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$grafana_node_job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Nginx UP Time [min]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_server_info / 60\n", "legendFormat": "Up Time" }
   ]
  },
  {
   "title": "Nginx Connection's Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_server_connections{status=~\"handled|accepted\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "NGinx Request's Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_requests{code!=\"total\"}[1m])) ",
     "legendFormat": "Request "
    }
   ]
  },
  {
   "title": "CPU Nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait "
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs "
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other "
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"nginx_node_ex\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle "
    }
   ]
  },
  {
   "title": "Memory Nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nginx_node_ex\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nginx_node_ex\"} - node_memory_MemFree_bytes{job=\"nginx_node_ex\"} - (node_memory_Cached_bytes{job=\"nginx_node_ex\"} + node_memory_Buffers_bytes{job=\"nginx_node_ex\"} + node_memory_SReclaimable_bytes{job=\"nginx_node_ex\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"nginx_node_ex\"} + node_memory_Buffers_bytes{job=\"nginx_node_ex\"} + node_memory_SReclaimable_bytes{job=\"nginx_node_ex\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nginx_node_ex\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"nginx_node_ex\"} - node_memory_SwapFree_bytes{job=\"nginx_node_ex\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Nginx",
   "type": "graph",
   "description": "Network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"nginx_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"nginx_node_ex\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"nginx_node_ex\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"nginx_node_ex\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}