route:
  group_by: ['alertname']
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram' # basic reciever, if alert doesn't match any matchers this reciever gets alert.
  routes:
  - receiver: 'telegram' 
    matchers:
    - severity=~"critical|warning" 
    
  - receiver: 'DeadMansSwitch'
    repeat_interval: 1m
    group_wait: 0s
    matchers:
    - severity="none"


receivers: 
- name: 'DeadMansSwitch'
  webhook_configs:
  - url: #how to [https://deadmanssnitch.com/docs]
    send_resolved: false
- name: 'telegram'  
  webhook_configs:
      - url: "http://alertmanager-telegram:8080/alerts"
        send_resolved: true
           


inhibit_rules:
  - source_matchers:
    - severity="critical"
    target_matchers:
    - severity="warning"
    equal: ['instance']